# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TracksLastPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('id_line', models.IntegerField()),
                ('speed', models.FloatField()),
                ('time', models.DateTimeField()),
                ('id_mobile', models.CharField(max_length=50)),
            ],
        ),
    ]
