# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_android', models.CharField(max_length=32)),
                ('time', models.FloatField()),
                ('distance', models.FloatField()),
                ('speed', models.FloatField()),
                ('rating', models.IntegerField()),
                ('linha', models.CharField(max_length=32)),
                ('car_or_bus', models.IntegerField()),
                ('rating_weather', models.IntegerField()),
                ('rating_bus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TracksPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_points', to='gotrack.Tracks')),
            ],
        ),
    ]
